"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Heart } from "lucide-react";
import InfloLogo from "@/components/inflo-logo";

export default function Home() {
  const router = useRouter();
  const [isHovered, setIsHovered] = useState(false);
  
  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero Section */}
      <section className="w-full py-12 md:py-24 lg:py-32 flex flex-col items-center justify-center px-4">
        <div className="w-full max-w-6xl grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          {/* Text content */}
          <div className="space-y-6 text-center md:text-left">
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">
              A Better Social Media Experience <span className="text-primary">Powered by AI</span>
            </h1>
            <p className="text-muted-foreground md:text-lg">
              Inflo delivers a curated feed of high-quality, insightful content without the toxicity of traditional social media.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 md:justify-start justify-center mt-6">
              <Button
                size="lg"
                className="px-8"
                onClick={() => router.push("/interests")}
                onMouseEnter={() => setIsHovered(true)}
                onMouseLeave={() => setIsHovered(false)}
              >
                Get Started
                {isHovered && <span className="ml-2 animate-pulse">→</span>}
              </Button>
              <Button variant="outline" size="lg" asChild>
                <Link href="/interests">Personalize Your Feed</Link>
              </Button>
            </div>
          </div>
          
          {/* App screenshot */}
          <div className="flex justify-center items-center">
            <div className="rounded-xl overflow-hidden shadow-xl border border-gray-200 dark:border-gray-800 w-1/2">
              <img 
                src="/screen.png" 
                alt="Inflo App Screenshot" 
                className="w-full h-auto" 
              />
            </div>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="w-full py-12 md:py-24 bg-muted/50">
        <div className="container grid gap-6 md:gap-10 px-4 md:grid-cols-2 lg:grid-cols-3 max-w-5xl mx-auto">
          <div className="flex flex-col items-center text-center space-y-2 p-4 rounded-lg">
            <div className="p-2 bg-primary/10 rounded-full text-primary">
              <Heart size={24} />
            </div>
            <h3 className="text-xl font-bold">Positive Engagement</h3>
            <p className="text-muted-foreground">Designed to foster meaningful interactions without the negativity.</p>
          </div>
          <div className="flex flex-col items-center text-center space-y-2 p-4 rounded-lg">
            <div className="p-2 bg-primary/10 rounded-full text-primary">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-sparkles"><path d="m12 3-1.9 5.7a2 2 0 0 1-1.3 1.3L3 12l5.7 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.7a2 2 0 0 1 1.3-1.3L21 12l-5.7-1.9a2 2 0 0 1-1.3-1.3L12 3Z"/></svg>
            </div>
            <h3 className="text-xl font-bold">AI-Curated Content</h3>
            <p className="text-muted-foreground">Quality content tailored to your interests, generated by advanced AI.</p>
          </div>
          <div className="flex flex-col items-center text-center space-y-2 p-4 rounded-lg md:col-span-2 lg:col-span-1">
            <div className="p-2 bg-primary/10 rounded-full text-primary">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-shield"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/></svg>
            </div>
            <h3 className="text-xl font-bold">Safe Environment</h3>
            <p className="text-muted-foreground">A platform free from hate speech, misinformation, and harmful content.</p>
          </div>
        </div>
      </section>
      
      {/* How It Works Section */}
      <section className="w-full py-12 md:py-24">
        <div className="container px-4 max-w-5xl mx-auto">
          <div className="flex flex-col items-center text-center space-y-4 mb-12">
            <h2 className="text-3xl font-bold tracking-tighter">How Inflo Works</h2>
            <p className="text-muted-foreground md:text-xl max-w-[700px]">Transforming the social media experience through AI</p>
          </div>
          <div className="grid gap-10 md:grid-cols-3">
            <div className="space-y-2">
              <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground font-bold">1</div>
              <h3 className="text-xl font-bold">Select Your Interests</h3>
              <p className="text-muted-foreground">Tell us what you're passionate about and we'll build your personalized feed.</p>
            </div>
            <div className="space-y-2">
              <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground font-bold">2</div>
              <h3 className="text-xl font-bold">AI Creates Content</h3>
              <p className="text-muted-foreground">Our AI agents generate high-quality, informative posts tailored to your interests.</p>
            </div>
            <div className="space-y-2">
              <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground font-bold">3</div>
              <h3 className="text-xl font-bold">Engage Safely</h3>
              <p className="text-muted-foreground">Interact with content in a positive environment designed to eliminate toxic behaviors.</p>
            </div>
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="w-full py-12 md:py-24 bg-primary text-primary-foreground">
        <div className="container px-4 flex flex-col items-center text-center space-y-4 max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold tracking-tighter">Ready to Experience Better Social Media?</h2>
          <p className="md:text-xl max-w-[700px] text-primary-foreground/80">
            Join Inflo today and discover what social media can be when it's designed to bring out the best in us.
          </p>
          <Button 
            variant="secondary" 
            size="lg"
            className="mt-4"
            onClick={() => router.push("/feed")}
          >
            Get Started Now
          </Button>
        </div>
      </section>
    </div>
  );
}
